### ISSUE TITLE
embedded mvwn does not work!

### ISSUE THREAD

**Issue by j75** [ammbra/micrometering-with-quarkus#2]
On Linux (Ubuntu 20.04) I have the following problem:
```
./mvnw compile quarkus:dev
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.224 s
[INFO] Finished at: 2022-03-23T17:04:51+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.7.1.Final:dev (default-cli) on project micrometering-with-quarkus: Detected Maven Version (3.6.3)  is not supported, it must be in [3.8.1,). -> [Help 1]
```
And indeed `./mvnw --version` =>
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/.../.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.14, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.13.0-37-generic", arch: "amd64", family: "unix"
```
With a **3.8.4** Maven version everything goes well and I can open the application in the browser etc...

**Comment by ammbra** [comment]
Hi,

Thank you for bringing this up. The project was started with Quarkus version 1.* and was migrated to version 2. However, I did not migrate the scripts as well.

Now it should not happen anymore.

**Comment by j75** [comment]
Hi!

I just updated the project, but the issue is still present:
```
ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.7.1.Final:dev (default-cli) on project micrometering-with-quarkus: Detected Maven Version (3.6.3)  is not supported, it must be in [3.8.1,). -> [Help 1]
[ERROR] 
```

And `./mvnw --version` still returns **Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)**

However I notice it displays
`Maven home: /home/.../.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3`

**Comment by j75** [comment]
Why this issue is closed? the problem is not solved IMHO as long as I cannot build the jar!

**Comment by ammbra** [comment]
The issue is closed as I upgraded the scripts and the wrapper. Please pull the latest changes.
Also, thank you very much for testing my sample project 👍  .
