### ISSUE TITLE
Cannot build native package!

### ISSUE THREAD

**Issue by j75** [ammbra/micrometering-with-quarkus#6]
1. 
``` java -version
openjdk version "11.0.14" 2022-01-18
OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 11.0.14+9-jvmci-22.0-b05)
OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (build 11.0.14+9-jvmci-22.0-b05, mixed mode, sharing)
```
2.
```${GRAALVM_HOME}/bin/gu list
ComponentId              Version             Component name                Stability                     Origin 
---------------------------------------------------------------------------------------------------------------------------------
graalvm                  22.0.0.2            GraalVM Core                  Supported                     
js                       22.0.0.2            Graal.js                      Supported                     
native-image             22.0.0.2            Native Image                  Early adopter                 github.com
```
3. `./mvnw package -Pnative` =>
```
[ERROR] Errors: 
[ERROR]   ExampleEndpointTest.findNonExistingLanguage » Runtime java.lang.RuntimeExcepti...
```
and in **target/surefire-reports/org.acme.endpoint.ExampleEndpointTest.txt** I have
```
Tests run: 5, Failures: 0, Errors: 1, Skipped: 4, Time elapsed: 4.519 s <<< FAILURE! - in org.acme.endpoint.ExampleEndpointTest
org.acme.endpoint.ExampleEndpointTest.findNonExistingLanguage  Time elapsed: 0.011 s  <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Unable to start HTTP server
Caused by: java.util.concurrent.ExecutionException: io.quarkus.runtime.QuarkusBindException
Caused by: io.quarkus.runtime.QuarkusBindException
```

So it seems to be a port error - should the command be run as `root` (or as other user)? is it possible to change the port? (BTW is it defined somewhere? running the application as `./mvnw compile quarkus:dev` shows that the standard **8080** Spring port  is used).
Should some environment variables be defined in order to make the native application building run correctly?

**Comment by ammbra** [comment]
If you have a process already running on 8080 port, it will attempt to use another port. You can either remove the other process running on 8080, or start your app with -Dquarkus.http.port=<yourcustomport>. Closing this now as is unrelated to the project. 

More about running Quarkus and overriding params can be found here: https://quarkus.io/guides/config. 

Good luck :)!

**Comment by j75** [comment]
Why did you close the issue without waiting for a reply from me? **This** is the problem, I don"t have anything listening to that port!
```
netstat -ant | grep LIST | grep 8080
```
returns nothing ! So I presume that it uses another port when compiling native, but which one?
Or maybe the tests are running in parallel, and then a port conflict occurs.

**Comment by ammbra** [comment]
I closed it as from your comment I understood that the issue was the port. The project uses Lombok as well, so please make sure that you have the latest version of this repo that includes the annotation RegisterForReflection. 

This project does compile to native, but when you start it, it won't work as in JVM mode because is using an embedded database. I added yesterday a comment in the README.md that another type of database should be used to be able to run in Native Mode. If you are seeking to run the examples from the Dzone article, I would suggest running it in JVM mode (simply mvn clean package). If that does not work for you either, I cannot help you further as I did not test it on a similar setup as yours.

**Comment by j75** [comment]
The issue is that in spite of what is written in the Readme, I cannot **compile** the native application. I tried to supply you with the messages I get, but from your answer I think that you have some peculiar configuration (environment variables? specific config files?) and that in your particular case it works, but in the general case it happens not to work!
